import "@testing-library/jest-dom";
import { fireEvent, render, waitFor } from "@testing-library/react";
import { Provider } from "react-redux";
import { StaticRouter } from "react-router-dom/server";
import store from "../../utils/store";
import Body from "../Body";

// we are trying to mock a fetch api
global.fetch = jest.fn(() => {
  return Promise.resolve({
    json: function () {
      return Promise.resolve(RESTAURANT_DATA);
    },
  });
});

test("Shimmer should load on HomePage", () => {
  const body = render(
    <StaticRouter>
      <Provider store={store}>
        <Body />
      </Provider>
    </StaticRouter>
  );

  const shimmer = body.getByTestId("shimmer");
    expect(shimmer.children.length).toBe(10);
});




test("Restaurant should load on HomePage", async() => {
  const body = render(
    <StaticRouter>
      <Provider store={store}>
        <Body />
      </Provider>
    </StaticRouter>
  );

  await waitFor(()=>expect(body.getByTestId("search-btn")));
  
  const resList = body.getByTestId("res-list");
    expect(resList.children.length).toBe(12);
});









// Integration Testing
test("Search for string(food) on HomePage", async() => {
  const body = render(
    <StaticRouter>
      <Provider store={store}>
        <Body />
      </Provider>
    </StaticRouter>
  );

  await waitFor(()=>expect(body.getByTestId("search-btn")));
  
  const input = body.getByTestId("search-input");
  fireEvent.change(input, {
    target: {
      value: "king"
    }
  });  

  const searchBtn = body.getByTestId("search-btn");
  fireEvent.click(searchBtn);
  const resList = body.getByTestId("res-list");
  expect(resList.children.length).toBe(1);
});




const RESTAURANT_DATA = {
  statusCode: 0,
  data: {
    cacheExpiryTime: 320,
    pages: 9,
    pageIndex: 0,
    scrubber: 0,
    filters: [
      {
        type: "FilterWidget",
        title: "Cuisines",
        key: "CUISINES",
        configType: "checkbox",
        visible: 1,
        options: [
          { option: "American", selected: 0, visible: 1 },
          { option: "Asian", selected: 0, visible: 1 },
          { option: "Bakery", selected: 0, visible: 1 },
          { option: "Bengali", selected: 0, visible: 1 },
          { option: "Beverages", selected: 0, visible: 1 },
          { option: "Biryani", selected: 0, visible: 1 },
          { option: "Burgers", selected: 0, visible: 1 },
          { option: "Chinese", selected: 0, visible: 1 },
          { option: "Combo", selected: 0, visible: 1 },
          { option: "Continental", selected: 0, visible: 1 },
          { option: "Desserts", selected: 0, visible: 1 },
          { option: "Fast Food", selected: 0, visible: 1 },
          { option: "Healthy Food", selected: 0, visible: 1 },
          { option: "Ice Cream", selected: 0, visible: 1 },
          { option: "Ice Cream Cakes", selected: 0, visible: 1 },
          { option: "Indian", selected: 0, visible: 1 },
          { option: "North Indian", selected: 0, visible: 1 },
          { option: "Pastas", selected: 0, visible: 1 },
          { option: "Pizzas", selected: 0, visible: 1 },
          { option: "Seafood", selected: 0, visible: 1 },
          { option: "Snacks", selected: 0, visible: 1 },
          { option: "South Indian", selected: 0, visible: 1 },
          { option: "Sweets", selected: 0, visible: 1 },
          { option: "Tandoor", selected: 0, visible: 1 },
          { option: "Thalis", selected: 0, visible: 1 },
          { option: "Tibetan", selected: 0, visible: 1 },
        ],
        detail: "",
        heading: "Cuisines",
        applicable: 1,
        searchable: 1,
      },
      {
        type: "FilterWidget",
        title: "Show Restaurants With",
        key: "SHOW_RESTAURANTS_WITH",
        configType: "checkbox",
        visible: 1,
        options: [
          { option: "Offers", selected: 0, visible: 1 },
          { option: "Pure Veg", selected: 0, visible: 1 },
        ],
        detail: "",
        heading: "Offers & More",
        applicable: 1,
        searchable: 0,
      },
    ],
    sorts: [
      {
        type: "SortWidget",
        key: "RELEVANCE",
        title: "Relevance",
        selected: 1,
        visible: 1,
        defaultSelection: true,
      },
      {
        type: "SortWidget",
        key: "DELIVERY_TIME",
        title: "Delivery Time",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "RATING",
        title: "Rating",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO",
        title: "Cost: Low to High",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO_H2L",
        title: "Cost: High to Low",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
    ],
    configs: {
      ribbons: {
        PREORDER: {
          type: "PREORDER",
          text: "Preorder",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 3,
        },
        EXCLUSIVE: {
          type: "EXCLUSIVE",
          text: "Exclusive",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 2,
        },
        NEW: {
          type: "NEW",
          text: "Newly Added",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 4,
        },
        REPEAT: {
          type: "REPEAT",
          text: "Repeat",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#D53D4C",
          bottomBackgroundColor: "#B02331",
          priority: 6,
        },
        CLOUD: {
          type: "CLOUD",
          text: "Daily Menus",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 5,
        },
        PREMIUM: {
          type: "PREMIUM",
          text: "Premium",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#8a584b",
          bottomBackgroundColor: "#583229",
          priority: 7,
        },
        PROMOTED: {
          type: "PROMOTED",
          text: "Promoted",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#3a3c41",
          bottomBackgroundColor: "#1e2023",
          priority: 1,
        },
      },
      croutons: {
        RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "${amount} extra levied on some restaurants",
        },
        SERVICEABLE_WITH_BANNER_RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "rain_crouton_4x",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Few restaurants unserviceable due to rains",
        },
      },
    },
    cards: [
      {
        cardType: "messageCard",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "messageCard",
          data: { message: "Rise & shine, it’s breakfast time!" },
          subtype: "welcome",
          sticky: 0,
        },
        parentWidget: false,
      },
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "topCarousel",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 635529,
                  creativeId: "rng/md/carousel/production/pneknawbadtvceqzwiep",
                  type: "restaurantCollectionV2",
                  link: "49301",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607188,
                  creativeId: "rng/md/carousel/production/oxe97jexxbnxqtbhg2zo",
                  type: "restaurantCollectionV2",
                  link: "11740",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607195,
                  creativeId: "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
                  type: "restaurantCollectionV2",
                  link: "56421",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "messageCard",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "messageCard",
          data: { message: "All Restaurants" },
          subtype: "sortedRestaurantCount",
          sticky: 1,
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "171006",
            name: "Haldiram's Prabhuji",
            uuid: "fd0c3fb5-07f3-4df5-81f8-cd91f59ccf91",
            city: "237",
            area: "Ushagram",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "bv991lrf91cg1zd1p3du",
            cuisines: ["Sweets", "Snacks", "South Indian"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            slaString: "29 MINS",
            lastMileTravel: 2.700000047683716,
            slugs: {
              restaurant: "haldirams-prabhuji-asansol-locality-ushagram",
              city: "asansol",
            },
            cityState: "237",
            address:
              "116, GT Road east, opp Bhanga Panchil, Asansol Locality, Asansol",
            locality: "Pathak Bari",
            parentId: 2945,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [{ type: "PROMOTED" }],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
              "cid=6443165~p=1~eid=00000187-7911-557a-058c-235400b1014b",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "2.7 kms",
            hasSurge: false,
            sla: {
              restaurantId: "171006",
              deliveryTime: 29,
              minDeliveryTime: 29,
              maxDeliveryTime: 29,
              lastMileTravel: 2.700000047683716,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.8",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "131013",
            name: "Appy's Kitchen (Cakes and Snacks)",
            uuid: "664079f4-20d6-4daa-b93c-0b47394c8ea8",
            city: "237",
            area: "Pathak Bari",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "kioltozpnctgzeaxg46o",
            cuisines: ["Desserts", "Pizzas", "Bakery"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            slaString: "26 MINS",
            lastMileTravel: 0.699999988079071,
            slugs: {
              restaurant:
                "appys-kitchen-cakes-and-snakes-hutton-road-burnpur-road",
              city: "asansol",
            },
            cityState: "237",
            address:
              "Annada Tower, Rasdanga more, Hutton Road, Asansol Locality, Asansol",
            locality: "Hutton Road",
            parentId: 35195,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "0.6 kms",
            hasSurge: false,
            sla: {
              restaurantId: "131013",
              deliveryTime: 26,
              minDeliveryTime: 26,
              maxDeliveryTime: 26,
              lastMileTravel: 0.699999988079071,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.9",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "360881",
            name: "Pizza King",
            uuid: "83cb9df0-daaf-4522-a7a5-090b3fbd455a",
            city: "237",
            area: "Ushagram",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "621a9b8537d01c2199280fd7da8092eb",
            cuisines: ["Pizzas", "American", "Burgers"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            slaString: "36 MINS",
            lastMileTravel: 0.800000011920929,
            slugs: {
              restaurant:
                "yash-chawla-by-pizza-king-asa_burnpur_extn-asa_burnpur_extn",
              city: "asansol",
            },
            cityState: "237",
            address: "HILL VIEW PARK SB GORAI ROAD PANI TANKI HIRAPUR  ASANSOL",
            locality: "Gorai Road",
            parentId: 4202,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
              restaurantId: "360881",
              deliveryTime: 36,
              minDeliveryTime: 36,
              maxDeliveryTime: 36,
              lastMileTravel: 0.800000011920929,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.7",
            totalRatings: 100,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "486187",
            name: "Madhuri",
            uuid: "5f4b94cf-623e-4fd8-955d-e1f3d0cee238",
            city: "237",
            area: "Ushagram",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "dwsxkfvgxr8c1rjsg59n",
            cuisines: ["North Indian"],
            tags: [],
            costForTwo: 8000,
            costForTwoString: "₹80 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 1.399999976158142,
            slugs: { restaurant: "madhuri-ushagram-ushagram", city: "asansol" },
            cityState: "237",
            address:
              "74/57 GT ROAD ASANSOL ASANSOL MUNICIPAL CORPORATION PASHIM BARDHAMAN  WB 713301",
            locality: "Gt Road",
            parentId: 291794,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "1.3 kms",
            hasSurge: false,
            sla: {
              restaurantId: "486187",
              deliveryTime: 23,
              minDeliveryTime: 23,
              maxDeliveryTime: 23,
              lastMileTravel: 1.399999976158142,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.3",
            totalRatings: 100,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "267397",
            name: "Cake Studio",
            uuid: "b6ce2d5e-a496-40ed-b0a8-3d19d0ae4d0f",
            city: "237",
            area: "Ushagram",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "4987ed519b0acd1eaf538f09787c003c",
            cuisines: ["Bakery"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            slaString: "33 MINS",
            lastMileTravel: 0.800000011920929,
            slugs: {
              restaurant: "cake-studio-asa_burnpur_extn-asa_burnpur_extn",
              city: "asansol",
            },
            cityState: "237",
            address: "BUDDHA MORE, OPP-PANI TANKI, ASANSOL, 713304",
            locality: "Sb Gorai Road",
            parentId: 55122,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
              restaurantId: "267397",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              lastMileTravel: 0.800000011920929,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 500,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "539837",
            name: "IS Cafe",
            uuid: "ef131e40-2a21-4394-b4dd-437157c27a73",
            city: "237",
            area: "Asa_Burnpur_Extn",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "tnbb8cmkeg9vnxg5efh1",
            cuisines: ["South Indian"],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            slaString: "26 MINS",
            lastMileTravel: 1.399999976158142,
            slugs: {
              restaurant: "is-cafe-asa_burnpur_extn-asa_burnpur_extn",
              city: "asansol",
            },
            cityState: "237",
            address:
              "87/48/ VIVEKANANDA PALLY WARD NO 84 WEST ISMILE WB 713301",
            locality: "Vivekananda Pally",
            parentId: 325659,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "20% off",
              shortDescriptionList: [
                {
                  meta: "20% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "20% off up to ₹50 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "20% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "20% off up to ₹50 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "1.3 kms",
            hasSurge: false,
            sla: {
              restaurantId: "539837",
              deliveryTime: 26,
              minDeliveryTime: 26,
              maxDeliveryTime: 26,
              lastMileTravel: 1.399999976158142,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.8",
            totalRatings: 100,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "134236",
            name: "Midos The Family Restaurant",
            uuid: "3897bb23-2088-4d79-9557-bc8ed6609b1a",
            city: "237",
            area: "Pathak Bari",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "csvq9c3yzj8dbbi9tymj",
            cuisines: ["Chinese", "Indian", "South Indian"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            slaString: "31 MINS",
            lastMileTravel: 1.100000023841858,
            slugs: {
              restaurant: "midos-the-family-restaurant-munshi-road-ushagram",
              city: "asansol",
            },
            cityState: "237",
            address:
              "Bus Stand, Munshi Bazar, Asansol Chittaranjan Road, Asansol Bazar, Asansol - 713301, Asansol Locality, Asansol",
            locality: "Munshi Road",
            parentId: 136026,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "1.1 kms",
            hasSurge: false,
            sla: {
              restaurantId: "134236",
              deliveryTime: 31,
              minDeliveryTime: 31,
              maxDeliveryTime: 31,
              lastMileTravel: 1.100000023841858,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.8",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "615676",
            name: "Wow! Momo",
            uuid: "3a2fdc84-4040-4b88-be20-756a12be2d13",
            city: "237",
            area: "Ushagram",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "90ac3da2963978f866177263fba805a7",
            cuisines: [
              "Tibetan",
              "Healthy Food",
              "Asian",
              "Chinese",
              "Snacks",
              "Continental",
              "Desserts",
              "Beverages",
            ],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            slaString: "29 MINS",
            lastMileTravel: 1.100000023841858,
            slugs: { restaurant: "wow-momo-asansol-ushagram", city: "asansol" },
            cityState: "237",
            address:
              "Holding no.6/New Adda market Complex, G.T.Road, Opp-City Bus Stand, Block-B, Ward no.8, Asansol- 713301, ASANSOL MUNICIPAL CORPORATION, PASCHIM BARDHAMAN, West",
            locality: "Gt Road",
            parentId: 1776,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "40% off",
              shortDescriptionList: [
                {
                  meta: "40% off | Use SPECIALS",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 on select items | Use code SPECIALS",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "40% OFF",
              shortDescriptionList: [
                {
                  meta: "Use SPECIALS",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 on select items | Use code SPECIALS",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "1.1 kms",
            hasSurge: false,
            sla: {
              restaurantId: "615676",
              deliveryTime: 29,
              minDeliveryTime: 29,
              maxDeliveryTime: 29,
              lastMileTravel: 1.100000023841858,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.3",
            totalRatings: 100,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "133022",
            name: "Minar Food Product",
            uuid: "749546d7-68bd-4cff-a4a8-f7c6ca8e297c",
            city: "237",
            area: "Pathak Bari",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "sjldscqeqt2lsbkzjdwz",
            cuisines: ["Bakery", "Pastas"],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 1.100000023841858,
            slugs: {
              restaurant: "minar-food-product-fairdeal-market-ushagram",
              city: "asansol",
            },
            cityState: "237",
            address:
              "88(25) GT Road, Fairdeal Market, near Asansol City Bus Stand",
            locality: "Fairdeal Market",
            parentId: 136370,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
              header: "40% off",
              shortDescriptionList: [
                {
                  meta: "40% off | Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
              header: "40% OFF",
              shortDescriptionList: [
                {
                  meta: "Use TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "40% off up to ₹80 | Use code TRYNEW",
                  discountType: "Percentage",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "1.1 kms",
            hasSurge: false,
            sla: {
              restaurantId: "133022",
              deliveryTime: 23,
              minDeliveryTime: 23,
              maxDeliveryTime: 23,
              lastMileTravel: 1.100000023841858,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 1000,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "187066",
            name: "Mahamaya Restaurant",
            uuid: "4b72c72c-5c46-477a-8e74-eae36451dd75",
            city: "237",
            area: "Chelidanga",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "ai34bwqsc4duy1tksmh9",
            cuisines: ["Chinese", "Biryani"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            slaString: "33 MINS",
            lastMileTravel: 1.5,
            slugs: {
              restaurant: "mayamaha-restaurent-co-allahabad-bank-burnpur-road",
              city: "asansol",
            },
            cityState: "237",
            address: "145, Sripally, S.B Gorai Road, Opp- Allahabad Bank",
            locality: "Sripally",
            parentId: 129786,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "1.5 kms",
            hasSurge: false,
            sla: {
              restaurantId: "187066",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              lastMileTravel: 1.5,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "2.7",
            totalRatings: 500,
            new: false,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "683338",
            name: "New Sri vrindavan sweets and snacks",
            uuid: "89c6dc54-4f0e-46fd-b0bf-73ae3c409c27",
            city: "237",
            area: "Only_Dom_Asaansol",
            totalRatingsString: "Too Few Ratings",
            cloudinaryImageId: "effa5a0e7653573718b12862b211ba47",
            cuisines: ["Sweets"],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 20,
            minDeliveryTime: 20,
            maxDeliveryTime: 20,
            slaString: "20 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
              restaurant:
                "new-sri-vrindavan-sweets-and-snacks-only_dom_asaansol-only_dom_asaansol",
              city: "asansol",
            },
            cityState: "237",
            address:
              "girja more, durga market, asansol municipal corporation, paschim bardhaman, 713304",
            locality: "Durga market",
            parentId: 407816,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
              restaurantId: "683338",
              deliveryTime: 20,
              minDeliveryTime: 20,
              maxDeliveryTime: 20,
              lastMileTravel: 0.8999999761581421,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "--",
            totalRatings: 0,
            new: true,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
      {
        cardType: "restaurant",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "restaurant",
          data: {
            type: "F",
            id: "684844",
            name: "Sitaram Mistanna Bhandar",
            uuid: "095a2d83-ee21-4966-bd9d-572ef49dd522",
            city: "237",
            area: "Ushagram",
            totalRatingsString: "Too Few Ratings",
            cloudinaryImageId: "6fee0afad5796186bdfa549037ba2e70",
            cuisines: ["Sweets", "Snacks"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            slaString: "30 MINS",
            lastMileTravel: 1,
            slugs: {
              restaurant: "sitaram-mistanna-bhandar-ushagram-ushagram-2",
              city: "asansol",
            },
            cityState: "237",
            address:
              "266/39, S.B.Gorai Road,Opposite-Tulsi Rani School,Asansol Municipal Corporation,Paschim Bardhaman,West Bengal-713301",
            locality: "S.B.Gorai Road",
            parentId: 261870,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
              fees: [
                { name: "distance", fee: 1900, message: "" },
                { name: "time", fee: 0, message: "" },
                { name: "special", fee: 0, message: "" },
              ],
              totalFees: 1900,
              message: "",
              title: "Delivery Charge",
              amount: "1900",
              icon: "",
            },
            availability: {
              opened: true,
              nextOpenMessage: "",
              nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
            lastMileTravelString: "1 kms",
            hasSurge: false,
            sla: {
              restaurantId: "684844",
              deliveryTime: 30,
              minDeliveryTime: 30,
              maxDeliveryTime: 30,
              lastMileTravel: 1,
              lastMileDistance: 0,
              serviceability: "SERVICEABLE",
              rainMode: "NONE",
              longDistance: "NOT_LONG_DISTANCE",
              preferentialService: false,
              iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "--",
            totalRatings: 0,
            new: true,
          },
          subtype: "basic",
        },
        parentWidget: false,
      },
    ],
    preorderSlots: [],
    slotInvalid: false,
    nextPageFetch: 0,
  },
  tid: "a10e093f-6e73-4dbb-9588-e77f7402c9a9",
  sid: "6gy0624c-f7e7-4bcd-be85-49ff44d34234",
  deviceId: "f00da47a-47a4-7cbc-d421-9abba14f76cf",
  csrfToken: "Xt5TZDFtZphk-7AzDxvndj003SaCs_yNHAs0X-yw",
};
